image: node:latest

stages:
  - build

pages: 
  stage: build
  script: 
  - npm install
  - mpx resumed render resume.json --theme mooser
  - mv resume.html public/index.html
  artifacts:
   paths: 
    - public
